name: AZTabFilter
main: com.github.crashdemons.aztectabfilter.AZTabPlugin
version: v0.20.3
author: crashdemons
description: Filters command tab-complete suggestions by whitelist.
website: https://github.com/crashdemons
load: STARTUP

api-version: 1.13

commands:
  aztabreload:
    description: reloads aztab config
    usage: /aztabreload
    permission: aztectabfilter.reload
    permission-message: You do not have permission to do this.

  aztabdump:
    description: toggles dumping command filtering information to console
    usage: /aztabdump
    permission: aztectabfilter.dump
    permission-message: You do not have permission to do this.


permissions:
  aztectabfilter.*:
    description: gives all permissions of the AZTab
    default: op
    children:
      aztectabfilter.reload: true
      aztectabfilter.bypass: true
      aztectabfilter.suggest: true
      aztectabfilter.dump: true

  aztectabfilter.suggest:
    description: Gives permission to see command suggestions at all (checked before filtering)
    default: true

  aztectabfilter.reload:
    description: Gives permission to reload AZTab config
    default: op

  aztectabfilter.bypass:
    description: Gives permission to bypass command filtering by AZTab
    default: op

  aztectabfilter.dump:
    description: Gives permission to enable console logging of filter results
    default: op
